-- psql --host=ec2-54-229-47-120.eu-west-1.compute.amazonaws.com --port=5432 --username=qkuoswcnucraae --password --dbname=d25enuf7ipg3bm


-- CREATE TABLE Products
--     (IdProduct SERIAL NUMERIC PRIMARY KEY,
--     )

-- CREATE TABLE `Products` (
--   `idProduct` int NOT NULL AUTO_INCREMENT,
--   `Sku` varchar(45) NOT NULL,
--   `Name` varchar(45) NOT NULL,
--   `Price` int unsigned NOT NULL,
--   `Type` varchar(45) NOT NULL,
--   `Size` int unsigned DEFAULT NULL,
--   `Height` int unsigned DEFAULT NULL,
--   `Width` int unsigned DEFAULT NULL,
--   `Length` int unsigned DEFAULT NULL,
--   `Weight` int unsigned DEFAULT NULL,
--   PRIMARY KEY (`idProduct`),
--   UNIQUE KEY `idProduct_UNIQUE` (`idProduct`),
--   UNIQUE KEY `Sku_UNIQUE` (`Sku`)
-- ) 

proces.